### ISSUE TITLE
ffvpn Default-Konfiguration

### ISSUE THREAD

**Issue by wyae** [freifunk-berlin/berlin.freifunk.net#37]
Für das OpnVPN-Profil FFVPN ist derzeit voreingestellt

(alt)  remote = 77.87.48.10 1194 udp

Es wäre vmtl. sinnvoll, dies auf den DNS-Namen vpn03.berlin.freifunk.net zu ändern. Dann funktioniert einerseits die Lastverteilung zwischen vpn03a und vpn03b, andererseits macht es Umzüge oder Erweiterungen des VPNs einfacher.

(besser)  remote = vpn03.berlin.freifunk.net 1194 udp

**Comment by andrenarchy** [comment]
Thanks for your report! This is already fixed in current master of the firmware-packages: https://github.com/freifunk-berlin/firmware-packages/blob/master/utils/freifunk-berlin-openvpn-files/uci-defaults/freifunk-berlin-openvpn#L22. So it will be included in the next release.

One remark: for future issues concerning the firmware it would be great if you can file them directly at https://github.com/freifunk-berlin/firmware.
